### ISSUE TITLE
Support array_contains in filter

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1115]
We support `column IN (<literal values>)` but don't support `array_contains(list_column, <literal_value>)`, even though this is quite useful.

To support this, we'll need to add new logic to handle parsing SQL into DataFusion logical expression:

https://github.com/lancedb/lance/blob/dacfda0cfaab62dc83871488ead90053f17d8c25/rust/src/io/exec/planner.rs#L295

And then add logic to handle translating the logical expressions into physical ones here:

https://github.com/lancedb/lance/blob/dacfda0cfaab62dc83871488ead90053f17d8c25/rust/src/io/exec/planner.rs#L368

See changes here for blueprint: https://github.com/lancedb/lance/pull/983/files

**Comment by westonpace** [comment]
`array_contains` was added to datafusion as https://github.com/apache/arrow-datafusion/commit/1dd1fbda716a43560b4d5cfe61bd79a9293bc46d which was added in version 28.  Should we hold off on this feature until version 28 is released?  Or is the datafusion function not needed?

**Comment by wjones127** [comment]
Looks like it was released recently. https://crates.io/crates/datafusion

Want to make a PR to upgrade the version of DataFusion? As part of that, we can upgrade Arrow to the same version that the new DataFusion version uses.

**Comment by westonpace** [comment]
As it turns out, `array_contains` was added in `28.0` but it isn't the correct function.  It is:

> returns true, if each element of the second array appearing in the first array, otherwise false.

In other words, a function that expects both sides to be arrays and returns if the second array is a subset of the first array.

This has recently been fixed.  There is now `array_has` (which is what we want I believe) and `array_has_all` (which is the old behavior).  However, that function won't be available until 29.0.0 so I think I'm back to parking this ticket while we wait on a release.

**Comment by wjones127** [comment]
Ah sorry for the wild goose chase. I honestly hadn't considered the possibility that DataFusion doesn't support it yet. We can park this for now.
