### ISSUE TITLE
Add Merge-On-Read index files

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1343]
Right now we handle deleted and moved rows poorly. For deleted rows, we have to read an individual fragments' deletion file. For moved rows, we consider them no longer part of the index, even though they theoretically should be query-able.

We can add a new file to better handle Merge-On-Read index modifications. This would store:

1. Deleted fragment_ids
2. Deleted row_ids
3. Remapped ids

The IO cost of deletions would be reduced because we just need to read this one file.

Additionally, we just need this file to perform "compaction" on indices.

**Comment by wjones127** [comment]
cc @westonpace @chebbyChefNEQ What do you think of this?

**Comment by eddyxu** [comment]
Should we just re-write the index. as well as #1342

**Comment by westonpace** [comment]
> Should we just re-write the index. as well as #1342
@eddyxu 

I think these are two different things.

 1. Always be able to query the index, regardless of any changes that have been made since the index was created
 2. "Update" an index to bring it up to the current dataset version

My original approach was to do both of these as the same operation but this ran into trouble because it's impossible to know the new row ids until the rewrite is committed (because that's the only point when we know the new fragment IDs).

@wjones127 How should a single unified merge-on-read file work with something like a multi-task compaction job?  This also means that rewrite and delete will conflict even if they don't modify the same fragments, but I don't think that's a big problem.

**Comment by wjones127** [comment]
> How should a single unified merge-on-read file work with something like a multi-task compaction job?

I was thinking it would be used for a separate update / compact index operation, so wouldn't relate to that.

> This also means that rewrite and delete will conflict even if they don't modify the same fragments, but I don't think that's a big problem.

Yeah, plus the remap probably needs to know the fragment ids for the current commit, so I was thinking this would have to be written in the commit loop.
