### ISSUE TITLE
Null supports in all encodings

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#16]
# Problem Statement

Apache Arrow supports Array with nulls. We should expect to store them efficiently on disk as well.

- [ ] PlainEncoding
- [x] VarBinaryEncoding

Dictionary encoding uses plain encoding for its index, so Null support can be done via Plain encoding.

**Comment by wjones127** [comment]
As is, the binary encoding can't differentiate between empty string and null. I wouldn't be surprised if later someone asks for that to be fixed.

Also, we don't error if provided null values in normal arrays. We seem to write zeros, though I'm not sure if that's just because the underlying bytes were zeroed or if we actually enforce that ourselves.
