### ISSUE TITLE
perf: f16 cosine kernel

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#1650]
Similar to L2 and dot kernels here https://github.com/lancedb/lance/blob/main/rust/lance-linalg/src/simd/f16.c

Provide cosine kernels, make sure the generated code are vectorized, and prepare benchmarks.

**Comment by wjones127** [comment]
Making a note: I think it still might be worth looking into doing the f16 math in f32 accumulators, since summing into an f16 value can be dangerous.

On AVX-512, there are instructions for:
1. Converting 16 f16 values to f32 values (`_mm512_cvtxph_ps` or `vcvtph2psx`) 
2. Multiplying and summing f32 values (`_mm512_fmadd_ps` or `vfmadd123ps`)

**Comment by eddyxu** [comment]
it is done
