### ISSUE TITLE
Lance Dataset Iteration does not honor batch_size

### ISSUE THREAD

**Issue by stabilize-ai** [lancedb/lance#1686]
When using lance.torch.kmeans.KMeans, the train batch size used by the iterator does not match the batch_size given by the user.

In particular, this [line](https://github.com/lancedb/lance/blob/e77eabfaadb5801a3fe3d28eaec935e18fc55f61/python/python/lance/torch/kmeans.py#L199). When the lance dataset is written with a multiple `.add(batch)` where batch is of size 1,000, the chunk size returned gets upper bounded by 1,000.

Further, even if the writing is done with a batch_size of 2,000; the reading batch_size gets upper bounded by 1,024

**Comment by chebbyChefNEQ** [comment]
Hi,

This is because we use `arrow::Scanner` under the hood. `arrow::Scanner` does not concat batches across row group boundaries; default row group size is 1024. I have opened a PR that addresses this issue by buffering and concating batch together in python.

Note that in the PR we do not try to hit the exact batch size specified as that would require complicated logic. Instead we yield a batch when ever adding a new batch would go over the batch size specified.

**Comment by stabilize-ai** [comment]
Thanks that will be very helpful - I will then implement a simple assert on my side to set the desired batch_size  to be either `< 1,024` or a `multiple of 1,024`
