### ISSUE TITLE
Compression for lance files

### ISSUE THREAD

**Issue by benmayersohn** [lancedb/lance#2037]
I'm reviving issue #682: any update on compression for lance files? I have a parquet file with roughly 25 million rows. There are 388 columns with the following dtypes:

| dtype  | count |
| ------------- | ------------- |
| int32 | 365 |
| categorical (large_string -> int32)  | 11  |
| double | 7 |
| bool  | 2  |
| int64 | 1 |
| date32[day]  | 1  |
| large_string  | 1  |

With LZ4 compression the parquet file is about 5.6 GB, but with the default settings in lance I get 26 `.lance` files adding up to 40.3 GB.

Love the project and appreciate your work on it!

**Comment by westonpace** [comment]
That's approximately 4 bytes per value which tracks pretty well with what we'd expect today.

Compression is something we're actively working on (https://github.com/lancedb/lance/issues/1929).  However, we are doing this in the form of more sophisticated encodings and not generalized compression.

This is both the way the industry is going (e.g. [procella](https://research.google/pubs/procella-unifying-serving-and-analytical-data-at-youtube/)) and important for us because it allows us to compress the data while still maintaining fast row-based lookups.

I don't know if we'll get exactly 5.6 GiB but I hope we will be quite a bit closer.

**Comment by benmayersohn** [comment]
Cool - good to know! I'll close this issue then 😄
