### ISSUE TITLE
Add logging for index generation

### ISSUE THREAD

**Issue by jaichopra** [lancedb/lance#855]
We currently don't have a verbose mode where you can log out ongoing status during index generation. For very large datasets/parameters where indexing takes a long time, it is a black box

**Comment by daikiad** [comment]
I agree as well. I am currently trying to handle around 1000 million data in Lance, but I'm having trouble figuring out how long it takes for the create_index process to complete. It would be really helpful if create_index could display a progress bar or something similar.

**Comment by jaichopra** [comment]
thanks @daikiad. i would be curious to learn more about your use case (at your scale) and to see how else we can help, happy to chat here/discord/zoom if you are interested

**Comment by daikiad** [comment]
Sorry, I mentioned 1000 million in the previous comments, but the correct range was actually 10 to 100 million data.

Currently, I am attempting to create vector representations of around 30 million PubMed literature data (including titles and abstracts) and manage them in lancedb. Earlier, I performed create_index(num_partitions=256, num_sub_vectors=96) on approximately 15 million pre-computed embeddings for testing purposes, and it completed in about 20 minutes.

Although I don't have a detailed understanding of the process behind vector index creation, I suspect that the k-means step might be the bottleneck. Am I correct in assuming this? Since k-means terminates based on convergence criteria, estimating the total time might be a bit challenging. However, it would be greatly appreciated if some progress logs or intermediate outputs could be generated during the process.

Thank you!

**Comment by MarkusOdenthal** [comment]
@daikiad, thanks for sharing your use case. I'm running into similar issues. I am working with a Wikipedia Dataset with 35 Mio. Vectors. And it isn't easy to see how long it takes. I also have the issue that I can't overwrite the old index if I want to create a new one. Do you have the same issue?

**Comment by daikiad** [comment]
@MarkusOdenthal Wow, I just encountered the same issue a few days ago. After creating the index once, when I tried to create the index again with different parameters, I received an error message saying "vectorindex already exists," which prevented me from creating the index.

I attempted to delete the index, but it seems that the lance library does not provide a built-in method to delete the index by default. I'm currently reading the source code to figure out how I can remove an existing vectorindex.

Also, I have a desire to switch between vectorindexes depending on the situation, such as using an accurate search or a faster but less accurate search. So, I thought it would be convenient if multiple vectorindexes were supported.

**Comment by eddyxu** [comment]
@daikiad @MarkusOdenthal Thanks for reporting this. You could use another "index" name to create a new index on the same column today.

We definitely should re-consider the behavior of whether we should consider the same "index name" as "overwrite" the index here.
